### PR TITLE
Spatial analog Processes enabled

### PR DESCRIPTION
**Pull request by nilshempelmann**
spatial analogs and map spatial anlogs slighly modified and integrated. 
tests passed. 

I didn't made test runs, since I don't know how what to write for the argument 'indice'. 

@huard are there a tutorial available may be based on public available datasets? 

I also propose to rename `map_spatial_analog` to `plot_spatial_analog` for consitent naming 

https://github.com/bird-house/flyingpigeon/issues/277

### CODE REVIEW

**Comment by huard** [comment]
candidate and target would be netCDF files holding different indices (annual mean temp, annual mean pr), and indices would be the name of the indices to perform the comparison. I'll try to come up with a test based on public data as well as a notebook example.

**Comment by nilshempelmann** [comment]
OK I got it. So the Process would be the following step after an indieces calculation process (from finch).

>name of the indices to perform the comparison. 

Means the variable name in the netCDF file, used to read the data? 
The notebook can be stored in the `notebooks` repository and linked into the documentation

**Comment by huard** [comment]
Correct. 
Correct.
Will do.

**Comment by nilshempelmann** [comment]
@cehbrecht checks failing, due to wokingdir missdeclaration. 
files are saved to curdir, not to the temp folder ... but self.workdir is set, can you help?

**Comment by cehbrecht** [comment]
@nilshempelmann I have started to fix `workir` ... see `wps_subset_continents.py` for example. But there is more to do. You don't need `rename_complexinput` ... should be fixed in pywps.

There is still something wrong with the test-suite ... haven't figured out. When I only run the `test_wps_subset_continent` test then it works.

**Comment by nilshempelmann** [comment]
@cehbrecht the workdirs are set in all Processes. 
``flyingpigeon.handler_common` is quite strange... please check this module. I also propose to move the only function there `wfs_common` to `eggshell.nc.nc_utils` may be even rename it to simply `wfs`

**Comment by nilshempelmann** [comment]
The output effects all Processes. So here is the issue: 
https://github.com/bird-house/flyingpigeon/issues/281

**Comment by cehbrecht** [comment]
@nilshempelmann I have skipped the subset continent/countries tests. They work when tested alone:
```
pytest tests/test_wps_subset_continents.py
```

... but not when running the test suite:
```
pytest -v tests/
```

I suppose there is still an issue with the `clipping`.

**Comment by nilshempelmann** [comment]
@cehbrecht 
> I suppose there is still an issue with the `clipping`.
OK will check it. Processes are running with good outputs. https://github.com/bird-house/flyingpigeon/issues/282 

@huard leave it to you to wrap up with `hanlder_common` https://github.com/bird-house/flyingpigeon/issues/281 issue and merge the PR and delete the branch

**Pull request merged**
