### PR TITLE
Switch on Subset processes

### PR DESCRIPTION
**Pull request by nilshempelmann**
Subset processes are re-enabled.
Shapefiles are in `flyingpigeon/data/shapefiles`.

### CODE REVIEW

**Comment by cehbrecht** [comment]
@nilshempelmann ... to make pep8 less painful you need to configure your editor:
https://birdhouse.readthedocs.io/en/latest/dev_guide.html#code-style

**Comment by cehbrecht** [comment]
@nilshempelmann please remove `.custom.cfg` ... it is probably a relict of previous version.

Also remove the temp file `pywps.pid`. Make sure your `.gitignore` is right. Start with the one from the template:
https://github.com/bird-house/cookiecutter-birdhouse/blob/master/%7B%7Bcookiecutter.project_repo_name%7D%7D/.gitignore

**Comment by cehbrecht** [comment]
@nilshempelmann ... not yet:

> Also remove the temp file pywps.pid. 

> Make sure your .gitignore is right. Start with the one from the template:
https://github.com/bird-house/cookiecutter-birdhouse/blob/master/%7B%7Bcookiecutter.project_repo_name%7D%7D/.gitignore

**Comment by nilshempelmann** [comment]
There is no ` pywps.pid` on my side and the .gitignore is based on cookiecutter ...

**Comment by cehbrecht** [comment]
ah ... there was something written:
> This file was deleted

Using `*.pid` might be safer.

**Comment by nilshempelmann** [comment]
@cehbrecht  Done :+1:

**Comment by cehbrecht** [comment]
@nilshempelmann satisfied :)

I will do a squash-merge ... the PR will then be just one commit on master.

**Comment by cehbrecht** [comment]
done :)

**Pull request merged**
