### PR TITLE
skip analog tests

### LINKED ISSUE #282: Tests for subset countries continents (clipping function)
Processes are running fine, but test are failing

### PR DESCRIPTION
**Pull request by huard**
## Overview

This PR fixes #282 

Changes:

* Skip analog tests

### CODE REVIEW

**Comment by huard** [comment]
@cehbrecht I broke the build with a push to master. I don't really understand why it fails.

**Comment by cehbrecht** [comment]
@huard ... the module `flyingpigeon.processes.wpsio` is missing. It is not in the github repo ... but maybe in your local sandbox?

**Comment by huard** [comment]
@cehbrecht Thanks! I was looking for a more complicated answer...

**Comment by cehbrecht** [comment]
@huard tests fail due to flake8 issues.

**Pull request merged**
