### PR TITLE
Modernized String Formatting and Exception Raising

### PR DESCRIPTION
**Pull request by Zeitsperre**
Hey everyone,

I wanted to perform a huge cleanup of the processes to make them more readable as well as handle a lot of issues that can become problems down the line (bare exceptions, identifying uncalled/unassigned variables and functions). This PR is a refactor that doesn' break the API but is a major cleanup/refactor of the code layout and some minor grammatical corrections. Feel free to add edits as required.

Best,

### CODE REVIEW

**Comment by huard** [comment]
You probably want to comment EO processes for the pavics branch, not the birdhouse master.

**Comment by cehbrecht** [comment]
@Zeitsperre @huard @nilshempelmann 
You want to clean up FP master to merge it to the pavics fork? I would suggest to reduce it to what is working and wanted. The FP development is save in the 1.2.x branch ... the work doesn't get lost.

**Comment by nilshempelmann** [comment]
I suggest to clean up FP and moving as many as possible to eggshell. Disable buggy processes.
@Zeitsperre what are you focussing on?

**Comment by Zeitsperre** [comment]
@nilshempelmann @cehbrecht 

I'm hoping to bring the Ouranosinc/master up to standard with changes made on BH/master and then merge the Ouranosinc/pavics branch into it (the hard part).

Mainly, I wanted to clean up the processes and make them more readable, raising exceptions as often as possible and finding broken processes (identified with TODO's). As @huard mentioned, there are still a lot of buggy processes that could be left alone here and disabled in our production (pavics) branch. Otherwise, like @cehbrecht mentions, I could just delete the ones that need a lot more work and we could copy them over to eggshell later. 

In order to move things to eggshell, the algorithms that work well still need to be cleaned up/simplified more. I'm not sure how to proceed for that (what's worth/not worth migrating?).

**Comment by huard** [comment]
There seems to be a problem with the R GOMP package, but that's probably unrelated to this PR.

**Pull request merged**
