### PR TITLE
Fix 274

### PR DESCRIPTION
**Pull request by huard**
Clean-up of subsetting operations: bbox and polygon from WFS server. 

I've created a base subsetter class to centralize common operations for subsetters. I've removed a lot of the tests which were fairly complex. We might want to revive them in the future. 

The first output is returned as a netCDF object, as usual, but multiple outputs are stored in a metalink file instead of a tar file. 

Note also that I removed cookie passing code, as I had no way of testing it.

### CODE REVIEW

**Comment by tomLandry** [comment]
This could get **very** handy for the analysis page of the Climate Data portal.

**Comment by huard** [comment]
There are now similar processes in a Finch branch using xarray. I think it would be worth comparing and benchmarking the two implementations.

**Comment by huard** [comment]
Should a mismatch raise an error or just be logged ?

**Comment by nilshempelmann** [comment]
If the date is not found in the files, ocgis is crashing with an error. 

I had a validation and set the date to the earliest/lates one possible. But this is a modification of the submitted job and the user needs to be informed. Usecase depending it is better to rise an error and point out the propper setting for the job.

**Comment by cehbrecht** [comment]
@huard @nilshempelmann merged. Thanks :)

**Pull request merged**
