### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by nilshempelmann**
## Overview

notbooks running with external testdata. 

need help to fix: https://github.com/bird-house/flyingpigeon/issues/322

should be tested on Pavics and Bovec

### CODE REVIEW

**Comment by nilshempelmann** [comment]
fixed https://github.com/bird-house/flyingpigeon/pull/325

**Comment by nilshempelmann** [comment]
@huard test takes a while. 
Are there small test data sets for running ensemble analyses? e.g. some files for a yearly aggegated indice?

**Comment by huard** [comment]
Not that I'm aware of, but should be possible to create one.

**Comment by nilshempelmann** [comment]
We can use the data created for Niger. They are 0.22 resolved so may be still to big.

**Pull request merged**
