### PR TITLE
Enabling skipped tests

### PR DESCRIPTION
**Pull request by huard**
I went through the tests that were skipped and re-activated those that I could fix. 

The sdm_gbiffetch test is too slow to run. Solution would be to enable BBox or limit.

### CODE REVIEW

**Comment by nilshempelmann** [comment]
enablbleing bbox is a very good idea also for other issues. sdm_gbiffetch can also be improved in performance by changing the species name. The current Fagus sylvatica has many records in the database which takes time to read out.

**Comment by huard** [comment]
Darn, you told me that before and I forgot. Will do shortly.

**Comment by huard** [comment]
Done, but there are problems in test_indices.py. One test is failing (I've not investigated) and there seems to be inconsistencies in the output prefix. So not ready to merge until someone gives it a check.

**Comment by nilshempelmann** [comment]
|test_indice_percentile could adopted to ||test_indice_dailypercentile 
which is implemented.
|

|
|

**Comment by huard** [comment]
Output file naming seems to be inconsistent based on the test results. Haven't instigated, maybe it's something else.

**Comment by nilshempelmann** [comment]
Here a job with sdm_gbiffetch using 'Quercus trojana' as species to be searched and bbox disabled.
performing time on bovec 4:35 min. May be still too long.
https://bovec.dkrz.de/monitor/details/b8dc4170-0e9a-437c-ba36-7dea71effc50/outputs 
https://bovec.dkrz.de/download/wpsoutputs/flyingpigeon/d7c4783c-99bd-11e7-aa8a-109836a7cf3a/tmpkiFT2v.png

**Comment by cehbrecht** [comment]
thanks :) merged now.

**Pull request merged**
