### PR TITLE
Ocgis regrid process

### LINKED ISSUE #217: Dedicated regridding process
I think it would be useful to have a dedicated regridding process.

### PR DESCRIPTION
**Pull request by huard**
New WPS using ocgis to regrid netcdf files.

Fixes #217 

Output is a json file storing the path to the output. Should we also add the first netcdf file itself ?

### CODE REVIEW

**Comment by nilshempelmann** [comment]
one test file as extra output was done to display it in a WMS. 
Is that still necessary to do so with a json? Can the WMS read the netCDF files (all of them) directly from json?

**Comment by nilshempelmann** [comment]
@cehbrecht 
I can't test the PR here. Internet is too weak today ...

**Comment by cehbrecht** [comment]
@huard 
the build is still not working. The buildout fails due to importing the flyingpigeon version which results in a long chain of other imports. We could work around this ... but the import that is failing will remain:

     from ocgis import RequestDataset
     /home/pingu/.conda/envs/flyingpigeon/lib/libesmf_fullylinked.so: undefined symbol: ESMC_InterfaceIntSet

@huard @bekozi
What would you propose to fix the import issue?

**Comment by huard** [comment]
I think I've forgotton to add esmf to environment (on top of esmpy). I guess I assumed it would pull the dependency automatically. Let me test it and get back to you.

**Comment by cehbrecht** [comment]
@huard 
It looks promising :) Tests still fail because there is now a new process which the `wps_caps` test does not know about. Please add `esmf_regrid` to
https://github.com/bird-house/flyingpigeon/blob/630243829a47b7473b4a6afaa9dc2faee4e51332/flyingpigeon/tests/test_wps_caps.py#L10

Tests are in alphabetical order. You can check locally with `make test`.

We can ignore codacy complains ... it is not our fault.

**Comment by huard** [comment]
Argh... sorry about this. Should have run make test. 

make test has a failure in test_R_imports.

**Comment by cehbrecht** [comment]
looks good :)

**Pull request merged**
